#Requires -Version 5.1
<#
.SYNOPSIS
    Writes the config.toml for the Kubernetes MCP server (containers/kubernetes-mcp-server)
    on the Windows host, in stdio mode (managed by the sbx MCP gateway).

.DESCRIPTION
    Creates %USERPROFILE%\.config\kubernetes-mcp-server\config.toml: stdio transport
    (no port - sbx starts the process via `sbx mcp add --command`), full scope by
    default (read-write, all toolsets), host kubeconfig. The sandbox-side Kit
    permission whitelist still limits the agent to read-only tools (docs/kubernetes-mcp-server.md).
    Secrets are deliberately NOT denied (required by the helm toolset, because
    Helm v3 stores releases as Secrets) - the generic tools can therefore read
    Kubernetes Secrets in full. DEVELOPMENT / NON-PRODUCTION ONLY.
    UTF-8 without BOM (the TOML parser rejects a BOM).

    Requires the server binary to be installed already
    (run local-scripts/install-kubernetes-mcp-server.ps1 first) - fails otherwise.

.PARAMETER InstallDir
    Directory holding kubernetes-mcp-server.exe. Default: %USERPROFILE%\.local\bin

.PARAMETER ConfigDir
    Target directory for config.toml. Default: %USERPROFILE%\.config\kubernetes-mcp-server

.PARAMETER Kubeconfig
    Path to the host kubeconfig. Default: %USERPROFILE%\.kube\config

.PARAMETER Toolsets
    MCP toolsets to enable. Default: all (core, config, helm, kcp, kiali, kubevirt, netobserv, tekton)

.PARAMETER ReadOnly
    Only expose read-only tools. Default: false (full scope; the sandbox Kit
    whitelist keeps the agent read-only). Enable with -ReadOnly:$true.

.PARAMETER Force
    Overwrite an existing config.toml.

.EXAMPLE
    .\configure-kubernetes-mcp-server.ps1

.EXAMPLE
    .\configure-kubernetes-mcp-server.ps1 -ReadOnly:$true -Toolsets core,config,helm -Force
#>
[CmdletBinding()]
param(
    [string]$InstallDir = (Join-Path $env:USERPROFILE ".local\bin"),
    [string]$ConfigDir = (Join-Path $env:USERPROFILE ".config\kubernetes-mcp-server"),
    [string]$Kubeconfig = (Join-Path $env:USERPROFILE ".kube\config"),
    [string[]]$Toolsets = @("core", "config", "helm", "kcp", "kiali", "kubevirt", "netobserv", "tekton"),
    [bool]$ReadOnly = $false,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$exePath = Join-Path $InstallDir "kubernetes-mcp-server.exe"
$configPath = Join-Path $ConfigDir "config.toml"

# --- Require an existing installation ---
if (-not (Test-Path $exePath)) {
    $msg = "kubernetes-mcp-server not found at '$exePath'.`n" +
        "Install it first:`n" +
        "  .\local-scripts\install-kubernetes-mcp-server.ps1"
    throw $msg
}

# --- Require a kubeconfig ---
if (-not (Test-Path $Kubeconfig)) {
    throw "kubeconfig not found at '$Kubeconfig'. Enable Docker Desktop Kubernetes or pass -Kubeconfig <path>."
}

# --- Do not clobber an existing config unless -Force ---
if ((Test-Path $configPath) -and -not $Force) {
    Write-Host "[config] $configPath already exists - use -Force to overwrite." -ForegroundColor Yellow
    return
}

# --- Build config.toml (stdio: no port, logs to stderr so stdout stays MCP-only) ---
$kubeconfigFwd = (Resolve-Path $Kubeconfig).Path -replace '\\', '/'
$toolsetsToml = ($Toolsets | ForEach-Object { '"' + $_ + '"' }) -join ', '
$readOnlyToml = if ($ReadOnly) { "true" } else { "false" }

$toml = @"
# Kubernetes MCP server - generated by local-scripts/configure-kubernetes-mcp-server.ps1
# Transport: stdio (started by the sbx MCP gateway via `sbx mcp add --command`)

# --- Scope: read_only = false exposes all read-write/exec tools ---
read_only = $readOnlyToml

# --- Toolsets (all by default) ---
toolsets = [$toolsetsToml]

# --- Cluster access from the host kubeconfig ---
kubeconfig = "$kubeconfigFwd"
cluster_provider_strategy = "kubeconfig"

# --- Logging: stdout is reserved for the MCP protocol in stdio mode ---
log_file = "stderr"
log_level = 2

# ============================================================================
# WARNING - DEVELOPMENT / NON-PRODUCTION ONLY
# No `denied_resources` entry: the generic tools (resources_get/resources_list)
# can read Kubernetes Secrets IN FULL (base64-encoded .data). This is required
# by the helm toolset, because Helm v3 stores releases as Secrets - denying the
# Secret kind breaks helm_list/helm_get/helm_status.
# NEVER point this configuration at a production cluster. For production,
# re-enable the block below (accepting that the helm toolset will no longer work).
# See docs/kubernetes-mcp-server.md -> "Sicherheit".
# ============================================================================
# [[denied_resources]]
# group = ""
# version = "v1"
# kind = "Secret"
"@

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
[System.IO.File]::WriteAllText($configPath, $toml)

# --- Summary ---
Write-Host ""
Write-Host "kubernetes-mcp-server config written (stdio):" -ForegroundColor Green
Write-Host ("  Config:      {0}" -f $configPath)
Write-Host ("  Kubeconfig:  {0}" -f $kubeconfigFwd)
Write-Host ("  Read-only:   {0}" -f $ReadOnly)
Write-Host ("  Toolsets:    {0}" -f ($Toolsets -join ", "))
Write-Host ""
Write-Host "WARNING: Secrets are NOT denied (required by helm). The generic tools can read" -ForegroundColor Yellow
Write-Host "         Kubernetes Secrets in full. DEVELOPMENT / NON-PRODUCTION ONLY." -ForegroundColor Yellow
Write-Host ""
Write-Host "Register with the sbx MCP gateway (sbx starts the server on the host, stdio):" -ForegroundColor Green
Write-Host ("  sbx mcp add k8s --command `"{0}`" --args `"--config,{1}`"" -f $exePath, $configPath)
