#!/usr/bin/env bash
# Docker + Kubernetes reachability for the TUI sidebar "Docker / Kubernetes" box.
# One-line report in startup-checks token format (name:OK | name:FAIL).
# Bounded timeouts so the check never hangs; set +e so one failure never aborts.
set +e

# Docker daemon reachable (isolated daemon in the sandbox microVM)?
if timeout 5 docker info >/dev/null 2>&1; then
  docker="docker:OK"
else
  docker="docker:FAIL"
fi

# Docker Desktop host daemon reachable (optional; DOCKER_HOST=tcp://host.docker.internal:2375)?
if timeout 5 docker -H tcp://host.docker.internal:2375 info >/dev/null 2>&1; then
  docker_host="docker-host:OK"
else
  docker_host="docker-host:FAIL"
fi

# Kubernetes cluster reachable? Uses the kubeconfig auto-generated by
# setup.startup (regenerate-kubeconfig.py). Without the .kube mount kubectl
# errors fast -> kubernetes:FAIL, which is the correct "not reachable" state.
# Self-healing: if the kubeconfig is missing (e.g. setup.startup raced the
# .kube virtiofs mount), regenerate it on the fly so the box recovers on the
# next poll instead of staying FAIL for the whole session.
if [ ! -f "$HOME/.kube/config" ]; then
  python3 "$HOME/.local/bin/regenerate-kubeconfig.py" 2>/dev/null
fi
if timeout 8 kubectl get --request-timeout=3s nodes >/dev/null 2>&1; then
  k8s="kubernetes:OK"
else
  k8s="kubernetes:FAIL"
fi

echo "$docker $docker_host $k8s"
