#!/usr/bin/env bash
# Docker + Kubernetes reachability for the TUI sidebar "Docker / Kubernetes" box.
# One-line report in startup-checks token format (name:OK | name:FAIL).
# Bounded timeouts so the check never hangs; set +e so one failure never aborts.
set +e

# Docker daemon reachable (isolated daemon in the sandbox microVM)?
if timeout 5 docker info >/dev/null 2>&1; then
  docker="docker:OK"
else
  docker="docker:FAIL"
fi

# Kubernetes cluster reachable? Uses the kubeconfig auto-generated by
# setup.startup (regenerate-kubeconfig.py). Without the .kube mount kubectl
# errors fast -> kubernetes:FAIL, which is the correct "not reachable" state.
if timeout 8 kubectl get --request-timeout=3s nodes >/dev/null 2>&1; then
  k8s="kubernetes:OK"
else
  k8s="kubernetes:FAIL"
fi

echo "$docker $k8s"
